'작성/수정자 : 백가희/백가희
'작성/수정일 : 2022.12.06/2022.12.06

@startuml Line.puml(id=EX1)
participant A #FF0
participant B #0F0

note over A
실선 그리기
----
코드
<code>
    ----
</code>

-- 실선에 텍스트 넣기 --
코드
<code>
    -- 실선에 텍스트 넣기 --
</code>

end note

note over B
이중 실선 그리기
====
코드
<code>
    ====
</code>

== 이중 실선에 텍스트 넣기 ==
코드
<code>
    == 이중 실선에 텍스트 넣기 ==
</code>
end note

note over A
점선 그리기
..
코드
<code>
    ..
</code>

.. 점선에 텍스트 넣기 ..
코드
<code>
    .. 점선에 텍스트 넣기 ..
</code>
end note
@enduml

@startuml Line.puml(id=EX2)
participant A #FF0
participant B #0F0

A ->(10) B : 10도 삐뚤어지겠어
A ->(50) B : 50도 삐뚤어지겠어
B ->(90) A : 나도 질 수 없지, 90도 가즈아
@enduml


@startuml
hide unlinked
participant Alice
participant Bob
participant Carol

Alice -> Bob : hello
@enduml
